server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: status
            values: [running]
    relabel_configs:
      # THIS SECTION ENSURES YOU CAN QUERY BY CONTAINER NAME
      - source_labels: ["__meta_docker_container_id"]
        target_label: "__path__"
        replacement: "/var/lib/docker/containers/$1/*.log"
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "stream"

    pipeline_stages:
      # We keep this to unwrap the Docker JSON file format
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      # We keep this so Grafana shows the real log time, not the time Promtail read it
      - timestamp:
          source: time
          format: RFC3339Nano
      # We output the clean log line. No regex parsing, no level extraction.
      - output:
          source: log
