- name: Download Cloudflared
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
    dest: /usr/local/bin/cloudflared
    mode: '0755'

- name: Verify Cloudflared Binary Works
  ansible.builtin.command: /usr/local/bin/cloudflared --version
  register: tunnel_cloudflared_version
  changed_when: false
  failed_when: tunnel_cloudflared_version.rc != 0

- name: Create Cloudflared Service File
  ansible.builtin.copy:
    dest: /etc/systemd/system/cloudflared.service
    mode: '0644'
    content: |
      [Unit]
      Description=cloudflared
      After=network.target

      [Service]
      TimeoutStartSec=0
      Type=notify
      ExecStart=/usr/local/bin/cloudflared tunnel run --token {{ cf_tunnel_token }}
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
  notify: Restart Cloudflared

- name: Reload Systemd Daemon
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'

- name: Ensure Tunnel Service is Running
  ansible.builtin.service:
    name: cloudflared
    state: started
    enabled: true

# trigger sum
- name: Wait for cloudflared to be active
  ansible.builtin.systemd:
    name: cloudflared
  register: tunnel_cloudflared_status
  retries: 5
  delay: 3
  until: tunnel_cloudflared_status.status.ActiveState == "active"
