- name: "Setup Monitoring Stack"
  block:
    - name: Create monitoring directory
      file:
        path: /opt/monitoring
        state: directory
        mode: '0755'

    - name: Copy monitoring files
      copy:
        src: "{{ playbook_dir }}/../../monitoring/" # navigating back from infra/ansible/ to root
        dest: /opt/monitoring/
        mode: '0644'

    - name: Deploy Monitoring Stack
      community.docker.docker_compose_v2:
        project_src: /opt/monitoring
        state: present
        pull: always # Ensures you always get the latest images
